version: "3"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  app:
    image: my-node-app
    ports:
      - 8080:3000
